# All parameters included in this file can be altered at the command line using the `--config` flag or by editing this file directly.

### Project-specific parameters
# The below are parameters that are project-specific and should be customized to reflect the project or dataset being processed and the local setup.

# file paths
results_dir: "../example-results/"
project_metadata: "../project-metadata/example-library-metadata-clustering.tsv"

### Processing parameters
# The below are parameters that are utilized to specify parameters specific to processing an individual library through the workflow.
# Changes to these are not required and can therefore be left at the default values.
# Although one may want to alter these parameters for exploratory purposes.

# seed to use for all steps
seed: 2021

# clustering parameters
cluster_type: "louvain" # The type of graph-based clustering to use for exploration
nearest_neighbours_min: 5 # The minimum value to use for a range of neareast neighbors values for testing
nearest_neighbors_max: 25 # The maximum value to use for a range of neareast neighbors values for testing
nearest_neighbors_increment: 5 # The increment to use when implementing the range number of nearest neighbors for cluster stats
overwrite_results: TRUE # A binary value indicating whether or not to overwrite any existing clustering results