data_dir: "data/Gawad_processed_data"
results_dir: "results/Gawad_processed_data"
mito_file: "data/Homo_sapiens.GRCh38.103.mitogenes.txt"
project_metadata: "project-metadata/gawad-library-metadata.tsv"
n_genes_pca: 2000 # The `n` number of highly variable genes to subset for PCA