# All parameters included in this file can be altered at the command line using the `--config` flag or by editing this file directly.

### Project-specific parameters
# The below are parameters that are project-specific and should be customized to reflect the project or dataset being processed and the local setup.

# file paths
results_dir: "example-results"
mito_file: "reference-files/Homo_sapiens.GRCh38.104.mitogenes.txt"
project_metadata: "project-metadata/example-library-metadata.tsv"

### Processing parameters
# The below are parameters that are utilized to specify parameters specific to processing an individual library through the workflow.
# Changes to these are not required and can therefore be left at the default values.
# Although one may want to alter these parameters for exploratory purposes.

# seed to use for all steps
seed: 2021

# miQC filtering parameters
prob_compromised_cutoff: 0.75 # Maximum miQC probability of cell being compromised

# manual filtering parameters
gene_detected_row_cutoff: 5 # Percent of cells a gene must be detected in
gene_means_cutoff: 0.1 # Mean gene expression minimum threshold
mito_percent_cutoff: 20 # Maximum percent mitochondrial reads per cell threshold
detected_gene_cutoff: 500 # Minimum number of genes detected per cell
umi_count_cutoff: 500 # Minimum UMI per cell

# dimensionality reduction parameters
n_genes_pca: 2000 # The `n` number of highly variable genes to subset for PCA

# clustering parameters
cluster_type: "louvain"
nearest_neighbors: 10
nearest_neighbors_min: 5 # The minimum value to use for a range of neareast neighbors values for exploration
nearest_neighbors_max: 25 # The maximum value to use for a range of neareast neighbors values for exploration
nearest_neighbors_increment: 5 # The increment to use when implementing the range number of nearest neighbors for cluster stats
overwrite_results: TRUE # A binary value indicating whether or not to overwrite any existing clustering results
