# All parameters included in this file can be altered at the command line using the `--config` flag or by editing this file directly.

### Optional clustering module specific parameters
goi_list: "data/anderson-single-cell/goi-lists/nb_goi_list.tsv"
organism: "Homo sapiens" 
provided_identifier: "SYMBOL"
sce_rownames_identifier: "ENSEMBL"
multi_mappings: "list" 
nearest_neighbors_max: 25 # The maximum value to use for a range of neareast neighbors values for exploration
nearest_neighbors_increment: 5 # The increment to use when implementing the range number of nearest neighbors for cluster stats
overwrite_results: TRUE # A binary value indicating whether or not to overwrite any existing clustering results
perform_mapping: TRUE