# All parameters included in this file can be altered at the command line using the `--config` flag or by editing this file directly.

### Optional integration module specific parameters
project_metadata: "example-data/project-metadata/example-integration-library-metadata.tsv"
results_dir: "example-results"
