# All parameters included in this file can be altered at the command line using the `--config` flag or by editing this file directly.

### Project-specific parameters
results_dir: "example-results"
integration_project_metadata: "example-data/project-metadata/example-integration-library-metadata.tsv"

### Processing parameters
threads: 1 # number of multiprocessing threads to use
integration_method: "fastMNN,harmony" # method(s) to be used for integration
batch_column: "library_id" # the name of the SCE column that contains batch labels